
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const FAQPage = () => {
  const faqs = [
    {
      question: "How does CreditCSV protect my financial data?",
      answer: "CreditCSV processes all your data locally in your browser. Your PDF statements are never uploaded to our servers, ensuring maximum privacy and security. We use client-side JavaScript to extract the data from your PDFs and convert it to CSV format entirely on your device."
    },
    {
      question: "Which credit card statements are supported?",
      answer: "We currently support statements from major credit card providers including Visa, Mastercard, American Express, and Discover. We're continuously working to add support for more statement formats."
    },
    {
      question: "How accurate is the conversion?",
      answer: "Our conversion algorithm is designed to be highly accurate for the supported statement formats. However, since credit card statement layouts can vary between issuers and can change over time, we recommend reviewing the output CSV to ensure all data has been extracted correctly."
    },
    {
      question: "Can I use CreditCSV on my mobile device?",
      answer: "Yes, CreditCSV works on modern mobile browsers. However, for the best experience, we recommend using a desktop or laptop computer, which makes file handling easier."
    },
    {
      question: "What if my statement format isn't recognized?",
      answer: "If your statement format isn't recognized, please contact us with details about your credit card issuer (without sharing any personal information). We're constantly improving our recognition algorithms and adding support for more statement formats."
    },
    {
      question: "Is there a limit to how many statements I can convert?",
      answer: "In the free version, you can convert a limited number of statements per month. For unlimited conversions, check out our premium plans."
    },
    {
      question: "Can I import the CSV directly to my accounting software?",
      answer: "Yes, the CSV files generated by CreditCSV can be imported into most accounting software and spreadsheet programs including Excel, Google Sheets, QuickBooks, and others."
    },
    {
      question: "Do you offer batch processing for multiple statements?",
      answer: "Batch processing of multiple statements is available in our premium plans. This feature allows you to convert multiple statements at once, saving you time."
    },
    {
      question: "How do I get help if I encounter issues?",
      answer: "If you encounter any issues or have questions, you can contact our support team through the contact form on our website. We aim to respond to all inquiries within 24 hours."
    },
    {
      question: "Is CreditCSV free to use?",
      answer: "We offer both free and premium plans. The free plan allows for a limited number of conversions per month, while our premium plans offer additional features like batch processing, advanced data extraction, and priority support."
    }
  ];

  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      
      <main className="flex-1 py-12">
        <div className="container">
          <div className="max-w-3xl mx-auto">
            <h1 className="text-3xl font-bold mb-2">Frequently Asked Questions</h1>
            <p className="text-gray-600 mb-8">Find answers to common questions about CreditCSV.</p>
            
            <Accordion type="single" collapsible className="w-full">
              {faqs.map((faq, index) => (
                <AccordionItem key={index} value={`item-${index}`}>
                  <AccordionTrigger className="text-left font-medium">
                    {faq.question}
                  </AccordionTrigger>
                  <AccordionContent className="text-gray-600">
                    {faq.answer}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
            
            <div className="mt-12 p-6 bg-gray-50 rounded-lg border border-gray-200">
              <h2 className="text-xl font-semibold mb-3">Still have questions?</h2>
              <p className="text-gray-600 mb-4">
                If you couldn't find the answer to your question, feel free to contact our support team.
              </p>
              <a 
                href="/contact" 
                className="text-brand-blue hover:text-brand-darkBlue font-medium inline-flex items-center"
              >
                Contact Support
                <svg 
                  className="ml-1 w-4 h-4" 
                  fill="none" 
                  stroke="currentColor" 
                  viewBox="0 0 24 24" 
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path 
                    strokeLinecap="round" 
                    strokeLinejoin="round" 
                    strokeWidth="2" 
                    d="M14 5l7 7m0 0l-7 7m7-7H3"
                  />
                </svg>
              </a>
            </div>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default FAQPage;
